spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/account
    username: ufutao
    password: ufutaoPublicPWD
  redis:
    host: redis
    port: 6379